Running on euler with following parameters : 
User : atabin
Model : /cluster/shadow/.lsbatch/1668375529.238482128
Data folder : /cluster/work/igp_psr/ai4good/group-1b/data/
Saving directory : /cluster/scratch/atabin//cluster/shadow/.lsbatch/1668375529.238482128/
Checkpoint path : /cluster/scratch/atabin/checkpoints//cluster/shadow/.lsbatch/1668375529.238482128/
usage: run.py [-h] [--data_dir DATA_DIR] [--checkpoint_path CHECKPOINT_PATH]
              [--save_dir SAVE_DIR]
              {upernet,cgnet,unet}
run.py: error: argument model: invalid choice: '/cluster/shadow/.lsbatch/1668375529.238482128' (choose from 'upernet', 'cgnet', 'unet')
Done!
